New mod:

* [Inserter Cranes for Pyanodons mods](https://mods.factorio.com/mod/InserterCranes-for-pymods)
* [Landfill Everything](https://mods.factorio.com/mod/LandfillEverythingU)

Pack:
* [FNEI](https://mods.factorio.com/mod/FNEI)
* [Helmod](https://mods.factorio.com/mod/helmod)
* [Rate Calculator](https://mods.factorio.com/mod/RateCalculator)
* [Bulk Rail Loader](https://mods.factorio.com/mod/railloader)
* [Rusty's Locale Utilities](https://mods.factorio.com/mod/rusty-locale)
* [VehicleSnap](https://mods.factorio.com/mod/VehicleSnap)
* [Additional Paste Settings](https://mods.factorio.com/mod/additional-paste-settings)
* [Blueprint Sandboxes](https://mods.factorio.com/mod/blueprint-sandboxes)
* [Bob's Adjustable Inserters](https://mods.factorio.com/mod/bobinserters)
* [Factory Search](https://mods.factorio.com/mod/FactorySearch)
* [Factorio Library](https://mods.factorio.com/mod/flib)
* [InfiniteInventory](https://mods.factorio.com/mod/InfiniteInventory)
* [Infinizoom](https://mods.factorio.com/mod/Infinizoom)
* [Inventory Sensor](https://mods.factorio.com/mod/Inventory%20Sensor)
* [Kruise_Kontrol](https://mods.factorio.com/mod/Kruise_Kontrol)
* [Ore Eraser (continued)](https://mods.factorio.com/mod/OreEraser)
* [Placeables](https://mods.factorio.com/mod/Placeables)
* [Quality of Life research](https://mods.factorio.com/mod/qol_research)
* [Queue To Front](https://mods.factorio.com/mod/QueueToFrontNG)
* [Realistic Decoration Cleanup](https://mods.factorio.com/mod/RealisticDecorationCleanup)
* [splatter_guard](https://mods.factorio.com/mod/splatter_guard)
* [Squeak Through](https://mods.factorio.com/mod/Squeak%20Through)
* [Factorio Standard Library (stdlib)](https://mods.factorio.com/mod/stdlib)
* [Stone Water Well](https://mods.factorio.com/mod/StoneWaterWell)
* [Teleporters](https://mods.factorio.com/mod/Teleporters)
* [ThickerLines](https://mods.factorio.com/mod/ThickerLines)
* [Underground Indicators](https://mods.factorio.com/mod/UndergroundIndicators)
* [Updated_Construction_Drones](https://mods.factorio.com/mod/Updated_Construction_Drones)
* [Bottleneck Lite](https://mods.factorio.com/mod/BottleneckLite)
* [Miniloader](https://mods.factorio.com/mod/miniloader)
* [Pipe Visualizer](https://mods.factorio.com/mod/PipeVisualizer)
* [Quick Item Search](https://mods.factorio.com/mod/QuickItemSearch)
* [PickerAtheneum](https://mods.factorio.com/mod/PickerAtheneum)
* [Picker Dollies](https://mods.factorio.com/mod/PickerDollies)
* [Picker Inventory Tools](https://mods.factorio.com/mod/PickerInventoryTools)
* [Belt Reverser](https://mods.factorio.com/mod/belt-reverserup)
* [Advanced Fluid Handling](https://mods.factorio.com/mod/underground-pipe-pack)
* [Advanced Fluid Handling For Pyanodon](https://mods.factorio.com/mod/advanced_fluid_handling_for_py)


for fun :
* [trainsaver](https://mods.factorio.com/mod/trainsaver)

LTN:
* [LTN - Logistic Train Network](https://mods.factorio.com/mod/LogisticTrainNetwork)
* [LTN_Combinator_Modernized](https://mods.factorio.com/mod/LTN_Combinator_Modernized)
* [LTN_Content_Reader](https://mods.factorio.com/mod/LTN_Content_Reader)
* [LTN Manager](https://mods.factorio.com/mod/LtnManager)

Pyanodon mods pack:
* [pycoalprocessing](https://mods.factorio.com/mod/pycoalprocessing)
* [pyfusionenergygraphics](https://mods.factorio.com/mod/pyfusionenergygraphics)
* [pyindustry](https://mods.factorio.com/mod/pyindustry)
* [pyrawores](https://mods.factorio.com/mod/pyrawores)
* [pyhightech](https://mods.factorio.com/mod/pyhightech)
* [pyraworesgraphics](https://mods.factorio.com/mod/pyraworesgraphics)
* [pyhightechgraphics](https://mods.factorio.com/mod/pyhightechgraphics)
* [pypetroleumhandling](https://mods.factorio.com/mod/pypetroleumhandling)
* [pyalienlife](https://mods.factorio.com/mod/pyalienlife)
* [pypetroleumhandlinggraphics](https://mods.factorio.com/mod/pypetroleumhandlinggraphics)
* [pycoalprocessinggraphics](https://mods.factorio.com/mod/pycoalprocessinggraphics)
* [pyfusionenergy](https://mods.factorio.com/mod/pyfusionenergy)
  
